version: '3.7'

services:

  postgres:
    image: postgres:16.2-alpine3.19
    container_name: db-pass-in
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
      - POSTGRES_DB=${DATASOURCE_DB}
    volumes:
      - 'db:/var/lib/postgresql/data'
    networks:
      - passin

  spring-boot-app:
    build:
      context: .
    container_name: api-pass-in
    ports:
      - "8080:8080"

    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
    networks:
      - passin


networks:
  passin:
    driver: bridge

volumes:
  db:
