apiVersion: apps/v1
kind: Deployment

metadata:
  name: passin-deployment
  labels:
    app: passin

spec:
  replicas: 5
  selector:
    matchLabels:
      app: passin
  template:
    metadata:
      labels:
        app: passin
    spec:
      containers:
      - name: passin
        image: wellingtondevps/pass-in-api:713e52d
        env:
          - name: DATASOURCE_URL
            value: jdbc:postgresql://db-pass-in:5432/pass_in
          - name: DATASOURCE_USERNAME
            value: ${DATASOURCE_USERNAME}
          - name: DATASOURCE_PASSWORD
            value: ${DATASOURCE_PASSWORD}
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 400m
            memory: 512Mi
        ports:
        - containerPort: 8080