apiVersion: apps/v1
kind: Deployment

metadata:
  name: passin-deployment
  labels:
    app: passin

spec:
  replicas: 5
  selector:
    matchLabels:
      app: passin
  template:
    metadata:
      labels:
        app: passin
    spec:
      containers:
      - name: passin
        image: wellingtondevps/pass-in-api:ec45a31
        env:
          - name: DATASOURCE_URL
            value: "postgresql://doadmin:AVNS_Ys870DKdzxGx6v75zs7@pass-in-do-user-16389043-0.c.db.ondigitalocean.com:25060/pass-in?sslmode=require"
          - name: DATASOURCE_USERNAME
            value: ${DATASOURCE_USERNAME}
          - name: DATASOURCE_PASSWORD
            value: ${DATASOURCE_PASSWORD}
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 400m
            memory: 512Mi
        ports:
        - containerPort: 8080