apiVersion: apps/v1
kind: Deployment

metadata:
  name: passin-deployment
  labels:
    app: passin

spec:
  replicas: 5
  selector:
    matchLabels:
      app: passin
  template:
    metadata:
      labels:
        app: passin
    spec:
      containers:
      - name: passin
        image: wellingtondevps/pass-in-api:981ba0a
        env:
          - name: DATASOURCE_URL
            valueFrom:
              secretKeyRef:
                name: dn-connection
                key: url
          - name: DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: dn-connection
                key: username
          - name: DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dn-connection
                key: password
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: "update"
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 400m
            memory: 512Mi
        ports:
        - containerPort: 8080