name: CI

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "SHA=$SHA" >> $GITHUB_OUTPUT

      - name: Build docker image
        run: docker build -t wellingtondevps/pass-in-api:${{steps.generate_sha.outputs.sha}} .

      - name: Log into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_TOKENUSERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Push docker image
        run: |
          docker push wellingtondevps/pass-in-api:${{steps.generate_sha.outputs.sha}}
          docker tag wellingtondevps/pass-in-api:${{steps.generate_sha.outputs.sha}} wellingtondevps/pass-in-api:latest
          docker push wellingtondevps/pass-in-api:latest

